spring:
  profiles:
    active: test
  application:
    name: SpringbootFastGPTApplication
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  mvc:
    async:
      request-timeout: 120000

server:
  tomcat:
    connection-timeout: 120000

fluent-mybatis:
  dbType: mysql